// <auto-generated />

using CheeseBot.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CheeseBot.Migrations
{
    [DbContext(typeof(CheeseBotDbContext))]
    partial class CheeseBotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("CheeseBot.EfCore.Entities.GuildSettings", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<string[]>("Prefixes")
                        .HasColumnType("text[]")
                        .HasColumnName("prefixes");

                    b.HasKey("GuildId")
                        .HasName("pk_guild_settings");

                    b.ToTable("guild_settings");
                });
#pragma warning restore 612, 618
        }
    }
}
